name = "Doodlemon Modpack"
author = "Macavity"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a08d1b559729577ed78c4eaf1bf6ec7b98441d943e84e5553954cf74910206"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
