name = "Doodlemon v0.8"
author = "Macavity"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a46c406d481157b7cef41feacf7de9fd6304814121f361d3a09e1d1bdc6600ed"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
