name = "Doodlemon v0.9"
author = "Macavity"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e6aba7a450de52728dd9590d23a2c3518d204697d8e6139fafe2271cf04b25f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
