name = "Doodlemon Modpack"
author = "Macavity"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1dd600a5562aa73e16be433234c7d0d7e0d3d21d237d0a338e848678971e67f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
