name = "Doodlemon Modpack"
author = "Macavity"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5b1871de47bd90daa06d12123f7f6a043143d8379e63a81828a37e302462923"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
