name = "Doodlemon Modpack"
author = "Macavity"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "026821b3709eb8406cb4a195a6d03e21ff9535ad8ab3b24038992c9f09df7343"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
